version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: store-app
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    container_name: store-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app